config/routes.rb
HoresaseBody::Application.routes.draw do
  root :to => 'horesases#index'
  resources :horesases

end

app/models/horesase.rb
class Horesase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/horesases_controller.rb
require 'net/http'

class HoresasesController < ApplicationController
  LOCAL_MEIGENS_PATH = '../horesase-boys/dist/meigens.json'
  MEIGENS_URL = 'http://horesase-boys.herokuapp.com/meigens.json'

  # GET /horesases
  # GET /horesases.json
  def index
    @horesases = Horesase.all
    @horesase_boys = Kaminari.paginate_array(JSON.parse(fetch_meigens)).page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @horesases }
    end
  end

  # POST /horesases
  # POST /horesases.json
  def create
    Horesase.transaction do
      params[:horesases].each do |_,data|
        @horesase = Horesase.find_or_create_by_id(data["id"])
        @horesase.body = data["body"]
        @horesase.save
      end
    end

    respond_to do |format|
      format.json { render json: @horesase, status: :created, location: @horesase }
    end

    rescue => e
    respond_to do |format|
      format.json { render json: @horesase.errors, status: :unprocessable_entity }
    end
  end

  private

  def fetch_meigens
    if File.exist?(LOCAL_MEIGENS_PATH)
      File.open(LOCAL_MEIGENS_PATH).read
    else
      Net::HTTP.get(URI.parse(MEIGENS_URL))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horesases_helper.rb
module HoresasesHelper
end

app/views/horesases/_form.html.haml
= form_for @horesase do |f|
  -if @horesase.errors.any?
    #error_explanation
      %h2= "#{pluralize(@horesase.errors.count, "error")} prohibited this horesase from being saved:"
      %ul
        - @horesase.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :id
    = f.number_field :id
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/horesases/edit.html.haml
%h1 Editing horesase

= render 'form'

= link_to 'Show', @horesase
\|
= link_to 'Back', horesases_path

app/views/horesases/index.html.haml
%h1 Listing meigens.json

= paginate @horesase_boys
%br

%form
  %table
    - @horesase_boys.each do |boy|
      %tr
        %td= boy['id']
        %td
          %img{:src => boy['image']}
        %td
          %textarea.horesase-body{'data-id' => boy['id']}= boy['body']
  %input#save{:type => 'button', :value => 'Save'}

%br
= paginate @horesase_boys

%br
= link_to 'New Horesase', new_horesase_path

:javascript
  var make_save_data = function(){
    var horesases = $.map(
      $('.horesase-body'),
      function(horesase_body){
        if(horesase_body.value != "")
          return {id: $(horesase_body).data('id'), body: horesase_body.value};
      }
    );
    return horesases;
  };
  $('#save').click(function(){
    var horesases = make_save_data();
    $.ajax({
      type: 'POST',
      url: '/horesases',
      data: {horesases: horesases},
      dataType: 'json',
      success: function(data){
        alert('Saveできた！');
      },
      error: function(XMLHttpRequest, textStatus, errorThrown) {
        alert('Saveできなかった…');
      }
    });
  });

app/views/horesases/new.html.haml
%h1 New horesase

= render 'form'

= link_to 'Back', horesases_path

app/views/horesases/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @horesase.id
%p
  %b Body:
  = @horesase.body

= link_to 'Edit', edit_horesase_path(@horesase)
\|
= link_to 'Back', horesases_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HoresaseBody
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield